version: "3.9"

services:
  traefik:
    image: traefik:v2.5.2
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./confs/traefik.toml:/traefik.toml
      - ./certs.json:/acme.json

  my_server:
    image: nginx
    networks:
      - overlay
    labels:
      - "traefik.http.routers.MY_SERVER_HTTP.entrypoints=insecure"
      - "traefik.http.routers.MY_SERVER_HTTP.rule=Host(`MY_DOMAIN`)"
      - "traefik.http.routers.MY_SERVER_HTTP.middlewares=https-redirect@docker"
      - "traefik.http.routers.MY_SERVER_HTTPS.entrypoints=secure"
      - "traefik.http.routers.MY_SERVER_HTTPS.rule=Host(`MY_DOMAIN`)"
      - "traefik.http.routers.MY_SERVER_HTTPS.tls=true"
      - "traefik.http.routers.MY_SERVER_HTTPS.tls.certresolver=letsencrypt"
      - "traefik.http.services.MY_SERVICE_NAME.loadbalancer.server.port=80"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"